### ISSUE TITLE
Small suggested paper edits

### ISSUE THREAD

**Issue by TomDonoghue** [JanCBrammer/biopeaks#16]
As part of the JOSS review (https://github.com/openjournals/joss-reviews/issues/2621), I've been reading the paper, with some small notes. 

Quick note:
- it seems a bit surprising to me that mean precision and sensitivity values are exactly the same (in the table). This could of course be correct, but it might be worth double checking there wasn't a copy/paste error here (?)

Small notes for the references:
- I don't think the Elgendi paper needs to reference the editor (or, at least, it is inconsistent for most papers you don't do this). The McKinney paper also lists editors, but from the PDF I'm not the listed editors are accurate, so I might check and remove there as well.  
- the 'Howell' paper is the only one that indicates a month as part of the date, and I think it probably doesn't need to do so
- I believe the numpy citation should have the first author's last name as `van der Walt` (all part of the last name). It seems to have been parsed to put the 'van der' as a middle name

**Comment by JanCBrammer** [comment]
>     * it seems a bit surprising to me that mean precision and sensitivity values are exactly the same (in the table)

@TomDonoghue, I now round the precision and sensitivity values to four instead of three decimal places, which makes it clear that they're different (cb89f3aa9338fdebc3f264b9cb04cb87ffa945b5).

I also formatted the references according to your suggestions: 416ad91766ca8e07ed3437f1ecc1f807e8e2fb03. You should be able to have a look at the updated paper preview [here](http://res.cloudinary.com/hju22ue2k/image/upload/v1601393483/g4nmuuw4lqkf91zjuihy.pdf) (let me know if the link is broken). I also replaced the old NumPy reference with the (now somewhat infamous) 2020 NumPy paper.
