### ISSUE TITLE
Less code to maintain?

### ISSUE THREAD

**Issue by DominiqueMakowski** [JanCBrammer/biopeaks#2]
I'm quite impressed by your work on this GUI, which got me thinking, couldn't you use NK as a dependency (since it basically doesn't really add any other deps that what you already have) here to have less code to maintain (since there's probably some duplication)? So NK could be focused on the algorithms and here on the GUI?

**Comment by JohnDoenut** [comment]
> since there's probably some duplication

@DominiqueMakowski, that's indeed a fair point. However, I want to keep the dependencies to a minimum. I especially want to avoid depending on scikit-learn and MNE, since these are quite heavy and in turn have a lot of dependencies. By sticking to this "lean" dependency design, I'm able to be more flexible with packaging, For now, people only need a standars Anaconda environment, which already comes with all my dependencies out of the box. Also, making a stand-alone installer at some point (e.g., a Windows .exe), is propably less of a hassle with fewer dependencies should I try it at some point.

**Comment by DominiqueMakowski** [comment]
Interesting, looking forward to the stand-alone installer!

on a side note, you'll be happy to know that MNE and others has become an optional dep now :) (only needed for the required functions, but not installed automatically nor needed for the package to run).

https://github.com/neuropsychology/NeuroKit/blob/3446907a08c61007666335838061ca679fb8fecb/setup.py#L22-L23

There is still scikit-learn, but I think it has become a fairly standard package now.
