### ISSUE TITLE
Add code coverage to tests

### ISSUE THREAD

**Issue by sappelhoff** [JanCBrammer/biopeaks#8]
related to JOSS review (https://github.com/openjournals/joss-reviews/issues/2621)

It would be great to add a tool that measures what proportion of your code is actually covered by the tests.

It's helpful to:
- give users a better impression of how far they can "trust" the tests
- give the developers a better idea of what aspects of the code are tested, and what aspects are not tested

This would be quite easy to implement, e.g., using pytest extensions and [codecov](https://codecov.io/) as in this repository: https://github.com/sappelhoff/pyprep

- you'd need `pytest-cov` (https://github.com/sappelhoff/pyprep/blob/da8e3a64cac7759e553d9dc219a88edc13f3b6cb/requirements-dev.txt#L10)
- you'd need to extend your GitHub Actions workflow (example: https://github.com/sappelhoff/pyprep/blob/da8e3a64cac7759e553d9dc219a88edc13f3b6cb/.github/workflows/python_tests.yml#L56-L60)

Finally, you could add a coverage badge next to your tests:

![image](https://user-images.githubusercontent.com/9084751/92302427-76641b80-ef6c-11ea-8aec-f30f020e9f34.png)

**Comment by TomDonoghue** [comment]
Somewhat related: it might be worth adding a note somewhere on the requirements for running the tests locally. As well as the standard of needing `pytest`, when trying to run the tests I got an error that `fixture 'qtbot' not found`, which I tracked to being because `pytest-qt` also being required. This isn't clearly noted anywhere. 

Somewhere, I would add a note of test-requirements, and maybe some instructions on running tests locally (this is perhaps most relevant in a contributor guide, as you would likely want contributors to run and check tests. 

As a note, I was able to run tests locally. I'm not sure of the coverage (adding that is a good idea), though the GUI tests looked (in terms of how many things popped up) fairly comprehensive.

**Comment by JanCBrammer** [comment]
> it might be worth adding a note somewhere on the requirements for running the tests locally

@TomDonoghue, I've included [testing instructions](https://jancbrammer.github.io/biopeaks/contributor_guide.html#tests) in the contributor guide (see 6685c6e6f9a49e8de59ffb2fd92fe4be1f30ca46).

**Comment by JanCBrammer** [comment]
> It would be great to add a tool that measures what proportion of your code is actually covered by the tests.

@sappelhoff, I now collect and report code coverage. However, the coverage is deceptively low (59%) since pytest-cov does not seem to pick up on code that is run within threads (see [here](https://codecov.io/gh/JanCBrammer/biopeaks/src/master/biopeaks/controller.py)). Looking into it.

**Comment by JanCBrammer** [comment]
Closing and transfering to #21, since original issue has been addressed.
