### ISSUE TITLE
Making community and contributing guidelines more visible

### ISSUE THREAD

**Issue by sappelhoff** [JanCBrammer/biopeaks#9]
related to JOSS review (https://github.com/openjournals/joss-reviews/issues/2621)

At the moment you have a [contributor's guide in the documentation](https://jancbrammer.github.io/biopeaks/contributor_guide.html). That's cool and I have some suggestions on how to make this more visible:

# New sections / re-ordering of README that is displayed on GitHub.
- most users will see this README as the first thing
- a new section `# Documentation` would be nice --> the heading will make it immediately obvious where people have to click 
    - currently the link to the docs is buried in "general info"
    - perhaps also worth thinking about which type of documentation you publish --> is it the "stable" version or "latest" (i.e., unreleased changes on `master`) or both?
- another new section `# Contributing` would be good with a brief sentence that contributions (of kind XYZ) are welcome ... and then provide a direct link to the contributors guide in the docs

# Code of Conduct
- currently there have not been many contributions from other people, but as soon as that starts to happen, you'd probably be better off with a code of conduct
- It's relatively low cost to add such a code and it can help if conflict ever arises
- see for example: https://www.contributor-covenant.org/
- GitHub organizations can also have a "default" code of conduct that gets "transmitted" to all repositories of that organization that do not yet have an own "code of conduct". This happens via a `.github` repository (see e.g., https://github.com/bids-standard/.github/) --> might be worth checking whether this is also possible for GitHub *users* (as opposed to organizations)
- docs for that: https://docs.github.com/en/github/building-a-strong-community/creating-a-default-community-health-file
- else, just add your own `CODE_OF_CONDUCT.md` to the root of this repo

**Comment by TomDonoghue** [comment]
I think these are great suggestions, and on the topic of adding direct links of brief summaries to the README, I might add a note on installation. Some brief info on installation is something I typically expect in the README. 

If I'm on Github, I basically just want to know "is this on PYPI". One option is to add a PYPI badge-link to the README (an example of this, and other badges here: https://github.com/neurodsp-tools/neurodsp). 

You might also just add a direct link from README -> installation page, and/or a mini section on the README that includes info, even if that's just something like 
```
`biopeaks` can be installed from pypi as
`pip install biopeaks`

For more information on installation, see the documentation page [link]
```

Note: I'm also from the JOSS review :)

**Comment by JanCBrammer** [comment]
@sappelhoff, @TomDonoghue, thanks for your advise and suggestions.

The README now has
* a more prominent link to the documentation
* a short section on installation and corresponding link to more detailled instructions
* a link to the contributor guide

See 7c1d10b25ab109ae6f8466d55c5009a789d23f67.

The contributor guide has been improved with more elaborate instructions (c2092bbef1dcc97515a73337fe8dac4243c24f8b).

I did some research on the code of conduct and added one to the repository (884bf6a2320839c9ac4db92a66244418d63fe345). The contributor/community aspect was not on my radar so much until now, since the development was mostly a solitary effort so far. But I hope for this to change in the future. Hence I appreciate you bringing the contributor/community aspect to my attention.

**Comment by sappelhoff** [comment]
Excellent, thanks. @TomDonoghue please feel free to re-open in case there were points that you feel have not been addressed.
